$(document).ready(function(){
    $("#signup-form").validate({
        rules:{
            fname:{
                required:true,
                minlength:4
            },
            surename:{
                required:true,
                minlength: 4
            },
            emailAddress:{
                required:true,
                email:true
            },
            password:{
                required:true,
                minlength:4
            },
            gender:{
                required:true
            }
        }
    })
})